(function(){
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const one=s=>document.querySelector(s);
  const addCss=()=>{if(document.querySelector('link[data-structural-v6]'))return;const l=document.createElement('link');l.rel='stylesheet';l.dataset.structuralV6='1';l.href=location.pathname.includes('/sites/')?'../../structural-v6.css':'structural-v6.css';document.head.appendChild(l)};
  const choose=(design,structure,industry)=>{
    const service=industry==='restaurant'?'menu-list':design==='bold'||industry==='gym'?'feature-pricing':design==='minimal'?'price-table':design==='photo'||industry==='hair'?'editorial-pricing':structure==='conversion'?'comparison-pricing':'editorial-pricing';
    const reviews=design==='luxury'?'lead-quote':design==='bold'?'numbered-proof':design==='friendly'?'staggered-notes':design==='minimal'?'review-rows':design==='photo'?'quote-wall':'lead-quote';
    const profile=industry==='hair'?'profile-magazine':industry==='gym'?'profile-stat':industry==='restaurant'?'profile-editorial':design==='minimal'?'profile-minimal':'profile-split';
    return {service,reviews,profile};
  };
  const renderServices=(c,mode)=>{const root=one('[data-service-groups]');if(!root)return;const groups=c.services?.groups||[];root.dataset.structure=mode;
    root.innerHTML=groups.map((g,gi)=>{
      const items=g.items||[];
      if(mode==='price-table')return `<section class="v6-service-group v6-price-table"><header><span>${String(gi+1).padStart(2,'0')}</span><h4>${esc(g.title)}</h4></header><div>${items.map(x=>`<article><div><h3>${esc(x.label)}</h3>${x.sub?`<p>${esc(x.sub)}</p>`:''}</div><strong>${esc(x.price)}</strong></article>`).join('')}</div>${g.note?`<p class="note">${esc(g.note)}</p>`:''}</section>`;
      if(mode==='menu-list')return `<section class="v6-service-group v6-menu-list"><header><small>MENU ${String(gi+1).padStart(2,'0')}</small><h4>${esc(g.title)}</h4></header><div class="v6-menu-lines">${items.map(x=>`<article><div><h3>${esc(x.label)}</h3>${x.sub?`<p>${esc(x.sub)}</p>`:''}</div><strong>${esc(x.price)}</strong></article>`).join('')}</div>${g.note?`<p class="note">${esc(g.note)}</p>`:''}</section>`;
      if(mode==='feature-pricing')return `<section class="v6-service-group v6-feature-pricing"><h4>${esc(g.title)}</h4><div class="v6-price-stack">${items.map((x,i)=>`<article class="${x.badge?'is-featured':''}"><div class="v6-price-index">${String(i+1).padStart(2,'0')}</div><div class="v6-price-copy">${x.badge?`<i>${esc(x.badge)}</i>`:''}<h3>${esc(x.label)}</h3>${x.sub?`<p>${esc(x.sub)}</p>`:''}</div><strong>${esc(x.price)}</strong></article>`).join('')}</div>${g.note?`<p class="note">${esc(g.note)}</p>`:''}</section>`;
      if(mode==='comparison-pricing')return `<section class="v6-service-group v6-comparison-pricing"><h4>${esc(g.title)}</h4><div class="v6-compare-grid">${items.map((x,i)=>`<article class="${x.badge||i===0?'is-featured':''}"><small>${x.badge?esc(x.badge):`PLAN ${String(i+1).padStart(2,'0')}`}</small><h3>${esc(x.label)}</h3><strong>${esc(x.price)}</strong>${x.sub?`<p>${esc(x.sub)}</p>`:''}</article>`).join('')}</div>${g.note?`<p class="note">${esc(g.note)}</p>`:''}</section>`;
      return `<section class="v6-service-group v6-editorial-pricing"><header><small>SERVICE ${String(gi+1).padStart(2,'0')}</small><h4>${esc(g.title)}</h4></header><div class="v6-editorial-list">${items.map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><h3>${esc(x.label)}</h3>${x.sub?`<p>${esc(x.sub)}</p>`:''}</div><strong>${esc(x.price)}</strong></article>`).join('')}</div>${g.note?`<p class="note">${esc(g.note)}</p>`:''}</section>`;
    }).join('')};
  const renderReviews=(c,mode)=>{const root=one('[data-reviews]');if(!root)return;const reviews=c.reviews||[];if(!reviews.length)return;root.dataset.structure=mode;
    if(mode==='lead-quote'){const [lead,...rest]=reviews;root.innerHTML=`<article class="v6-lead-review"><span>“</span><p>${esc(lead.body)}</p><strong>${esc(lead.name)}</strong></article>${rest.length?`<div class="v6-review-list">${rest.map(x=>`<article><p>“${esc(x.body)}”</p><strong>${esc(x.name)}</strong></article>`).join('')}</div>`:''}`;return}
    if(mode==='numbered-proof'){root.innerHTML=reviews.map((x,i)=>`<article class="v6-proof-review"><b>${String(i+1).padStart(2,'0')}</b><p>${esc(x.body)}</p><strong>${esc(x.name)}</strong></article>`).join('');return}
    if(mode==='review-rows'){root.innerHTML=reviews.map((x,i)=>`<article class="v6-review-row"><span>${String(i+1).padStart(2,'0')}</span><p>${esc(x.body)}</p><strong>${esc(x.name)}</strong></article>`).join('');return}
    if(mode==='quote-wall'){root.innerHTML=`<div class="v6-quote-wall">${reviews.map((x,i)=>`<article class="q${(i%3)+1}"><p>“${esc(x.body)}”</p><strong>${esc(x.name)}</strong></article>`).join('')}</div>`;return}
    root.innerHTML=reviews.map((x,i)=>`<article class="v6-note-review n${(i%2)+1}"><p>“${esc(x.body)}”</p><strong>${esc(x.name)}</strong></article>`).join('')};
  const renderProfile=(c,mode)=>{const p=one('.industry-profile');if(!p)return;p.dataset.structure=mode;const copy=p.querySelector('.industry-profile-copy'),photo=p.querySelector('.industry-profile-photo');if(!copy||!photo)return;
    if(mode==='profile-stat'){const name=copy.querySelector('h3')?.textContent||c.brand||'';const body=copy.querySelector('p')?.textContent||'';copy.innerHTML=`<small>TRAINER / PROFILE</small><div class="v6-profile-kicker">01</div><h2>${esc(name)}</h2><p>${esc(body)}</p>`;return}
    if(mode==='profile-magazine'){const name=copy.querySelector('h3')?.textContent||c.brand||'';const body=copy.querySelector('p')?.textContent||'';copy.innerHTML=`<small>PROFILE / STORY</small><h2>${esc(name)}</h2><blockquote>${esc(body)}</blockquote>`;return}
    if(mode==='profile-editorial'){const name=copy.querySelector('h3')?.textContent||c.brand||'';const body=copy.querySelector('p')?.textContent||'';copy.innerHTML=`<small>OUR PLACE</small><h2>${esc(name)}</h2><p class="v6-dropcap">${esc(body)}</p>`;return}
    if(mode==='profile-minimal')p.classList.add('v6-profile-minimal')};
  window.applyStructuralV6=function(config){try{addCss();const c=config||window.SITE_CONFIG||{};const design=document.body.dataset.design||c.layout?.design||'minimal';const structure=c.layout?.structure||'standard';const industry=document.body.dataset.industry||c.industryProfile?.key||'general';const modes=choose(design,structure,industry);document.body.dataset.serviceStructure=modes.service;document.body.dataset.reviewStructure=modes.reviews;document.body.dataset.profileStructure=modes.profile;renderServices(c,modes.service);renderReviews(c,modes.reviews);renderProfile(c,modes.profile)}catch(err){console.error('Structural V6 failed',err)}};
})();